### ISSUE TITLE
Group related output

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/link-checker#12]
We often have the same link 5 times on the website, once per language. When a page is removed and yields 404 now, the link checker reports this error 5 times in 5 completely different points in the output.

Ideally, I would like to see these 5 problems in one place.

**Comment by dcdunkan** [comment]
Grouping related output has been in my mind since the re-write. Too lazy to do it. I'll look into it.

**Comment by dcdunkan** [comment]
Done. Here's a sample output:

![image](https://github.com/grammyjs/link-checker/assets/70066170/fed47437-0d10-4e36-853c-ca7a43f0b594)

**Comment by rojvv** [comment]
That is fire!
